import os
from typing import Optional
from fastapi import FastAPI, Query
from fastapi.staticfiles import StaticFiles

from app.schemas import (
    AskRequest,
    AskResponse,
    RagRequest,
    RagResponse,
    CompareRequest,
    CompareResponse,
    OrchestrateRequest,
    OrchestrateResponse
)
from app.services.ollama_service import generate_answer
from app.services.knowledge_service import (
    get_raw_documents,
    get_knowledge_summary,
    load_knowledge_base,
    build_knowledge_base
)
from app.services.rag_service import run_rag_pipeline, run_comparison
from app.services.orchestrator import orchestrate_workflow

app = FastAPI(
    title="University Knowledge Assistant",
    description="An AI assistant API powered by Code Llama, local embeddings, RAG retrieval, and microservice orchestration",
    version="1.0.0"
)


# ==========================================
# Exercise 1 Endpoints (Preserved untouched)
# ==========================================

@app.get("/api/health")
def health_check():
    """Minimal health check endpoint."""
    return {"status": "ok"}


@app.post("/api/ask", response_model=AskResponse)
async def ask_question(payload: AskRequest):
    """Receive a student question and return the response generated by Code Llama via Ollama."""
    answer = await generate_answer(payload.question)
    return AskResponse(answer=answer)


# ==========================================
# Exercise 2: Knowledge Base Inspection API
# ==========================================

@app.get("/api/knowledge/summary")
def get_kb_summary():
    """Retrieve high-level summary of the knowledge base (document count, chunk count, dimensions)."""
    return get_knowledge_summary()


@app.get("/api/knowledge/documents")
def list_documents():
    """List original university policy documents and their content for inspection."""
    return get_raw_documents()


@app.get("/api/knowledge/chunks")
def list_chunks(doc_id: Optional[str] = Query(None, description="Filter chunks by document ID")):
    """List generated chunks along with embedding dimensions and vector samples."""
    kb = load_knowledge_base()
    if not kb:
        return {"chunks": [], "status": "not_indexed"}

    chunks = kb.get("chunks", [])
    if doc_id:
        chunks = [c for c in chunks if c.get("doc_id") == doc_id]

    inspected_chunks = []
    for c in chunks:
        vec = c.get("embedding", [])
        sample_vector = [round(x, 4) for x in vec[:5]] if vec else []
        inspected_chunks.append({
            "chunk_id": c.get("chunk_id"),
            "doc_id": c.get("doc_id"),
            "doc_title": c.get("doc_title"),
            "section": c.get("section"),
            "text": c.get("text"),
            "char_count": c.get("char_count"),
            "word_count": c.get("word_count"),
            "vector_dimension": len(vec),
            "vector_sample": sample_vector,
            "full_vector": vec
        })

    return {
        "status": "ready",
        "total": len(inspected_chunks),
        "chunks": inspected_chunks
    }


@app.post("/api/knowledge/index")
async def trigger_indexing():
    """Trigger the document chunking and real embedding generation pipeline."""
    result = await build_knowledge_base()
    return {
        "status": "success",
        "message": "Knowledge base indexed successfully.",
        "summary": result.get("metadata")
    }


# ==========================================
# Exercise 3: RAG & Comparison API Endpoints
# ==========================================

@app.post("/api/rag", response_model=RagResponse)
async def ask_rag(payload: RagRequest):
    """
    Exercise 3 RAG Pipeline:
    Question -> Query Embedding -> Cosine Similarity -> Top-K Retrieval -> Augmented Context -> Code Llama.
    """
    result = await run_rag_pipeline(payload.question, top_k=payload.top_k)
    return RagResponse(**result)


@app.post("/api/compare", response_model=CompareResponse)
async def compare_answers(payload: CompareRequest):
    """
    Exercise 3 Comparison Pipeline:
    Executes both Direct LLM and RAG pipelines to demonstrate how retrieved evidence impacts generation.
    """
    result = await run_comparison(payload.question, top_k=payload.top_k)
    return CompareResponse(**result)


# ===================================================
# Exercise 4: Microservice Orchestration Endpoint
# ===================================================

@app.post("/api/orchestrate", response_model=OrchestrateResponse)
async def orchestrate_request(payload: OrchestrateRequest):
    """
    Exercise 4 Orchestration Pipeline:
    Coordinates workflow across independent microservices:
    Application Service (:8000) -> Retrieval Service (:8001) -> LLM Service (:8002).
    Returns grounded answer, retrieved chunks, and an exact execution trace with real timings.
    """
    result = await orchestrate_workflow(payload.question, top_k=payload.top_k)
    return result


# ===================================================
# Week 4 Evaluation API Endpoints (Read-Only Data)
# ===================================================
import json

@app.get("/api/week4/metrics")
def get_week4_metrics():
    """Retrieve real evaluation metrics for Code Llama 7B, Phi-3 Mini, and Qwen 2.5 3B."""
    metrics_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "week-4", "results", "evaluation_metrics.json"))
    if os.path.exists(metrics_path):
        with open(metrics_path, "r", encoding="utf-8") as f:
            return json.load(f)
    return {"error": "Metrics file not found", "models": []}


@app.get("/api/week4/repository-analysis")
def get_week4_repo_analysis():
    """Retrieve Exercise 6 codebase understanding evaluation results."""
    repo_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "week-4", "results", "exercise6_repository_analysis.json"))
    if os.path.exists(repo_path):
        with open(repo_path, "r", encoding="utf-8") as f:
            return json.load(f)
    return {"error": "Repository analysis file not found", "results": []}


@app.get("/api/week4/questions")
def get_week4_questions():
    """Retrieve Week 4 evaluation question dataset."""
    q_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "week-4", "data", "evaluation_questions.json"))
    if os.path.exists(q_path):
        with open(q_path, "r", encoding="utf-8") as f:
            return json.load(f)
    return {"error": "Questions file not found", "questions": []}


# Mount static directory for frontend UI
static_dir = os.path.join(os.path.dirname(__file__), "static")
if os.path.exists(static_dir):
    app.mount("/", StaticFiles(directory=static_dir, html=True), name="static")

