import os
from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles

from app.schemas import AskRequest, AskResponse
from app.services.ollama_service import generate_answer

app = FastAPI(
    title="University Knowledge Assistant",
    description="An AI assistant API powered by Code Llama running via Ollama",
    version="1.0.0"
)


@app.get("/api/health")
def health_check():
    """Minimal health check endpoint."""
    return {"status": "ok"}


@app.post("/api/ask", response_model=AskResponse)
async def ask_question(payload: AskRequest):
    """Receive a student question and return the response generated by Code Llama via Ollama."""
    answer = await generate_answer(payload.question)
    return AskResponse(answer=answer)


# Mount static directory for frontend UI
# Defined after API routes so /api/* endpoints are matched first
static_dir = os.path.join(os.path.dirname(__file__), "static")
if os.path.exists(static_dir):
    app.mount("/", StaticFiles(directory=static_dir, html=True), name="static")
