from pydantic import BaseModel, Field


class AskRequest(BaseModel):
    question: str = Field(
        ...,
        min_length=1,
        description="The question or prompt submitted by the student",
        examples=["Explain the difference between a process and a thread."]
    )


class AskResponse(BaseModel):
    answer: str = Field(
        ...,
        description="The response generated by the local language model"
    )
