from typing import List
from pydantic import BaseModel, Field


# ==========================================
# Exercise 1 Schemas (Preserved untouched)
# ==========================================

class AskRequest(BaseModel):
    question: str = Field(
        ...,
        min_length=1,
        description="The question or prompt submitted by the student",
        examples=["Explain the difference between a process and a thread."]
    )


class AskResponse(BaseModel):
    answer: str = Field(
        ...,
        description="The response generated by the local language model"
    )


# ==========================================
# Exercise 3 Schemas (RAG & Comparison)
# ==========================================

class RetrievedChunk(BaseModel):
    chunk_id: str = Field(..., description="Unique chunk identifier")
    doc_id: str = Field(..., description="Source document ID")
    doc_title: str = Field(..., description="Human-readable document title")
    section: str = Field(..., description="Section title where chunk originated")
    similarity_score: float = Field(..., description="Cosine similarity score relative to query")
    text: str = Field(..., description="Context content text")


class RagRequest(BaseModel):
    question: str = Field(
        ...,
        min_length=1,
        description="The university question submitted by the student",
        examples=["What is the minimum attendance requirement and can it be condoned?"]
    )
    top_k: int = Field(
        default=3,
        ge=1,
        le=10,
        description="Number of most relevant context chunks to retrieve"
    )


class RagResponse(BaseModel):
    question: str
    answer: str
    retrieved_chunks: List[RetrievedChunk]
    grounding_summary: str


class CompareRequest(BaseModel):
    question: str = Field(
        ...,
        min_length=1,
        description="Question to compare across Direct LLM and RAG",
        examples=["What happens if my CGPA falls below 5.0?"]
    )
    top_k: int = Field(
        default=3,
        ge=1,
        le=10,
        description="Number of context chunks to retrieve for the RAG arm"
    )


class CompareResponse(BaseModel):
    question: str
    direct_answer: str
    rag_answer: str
    retrieved_chunks: List[RetrievedChunk]
