from typing import List, Optional
from pydantic import BaseModel, Field


# ==========================================
# Exercise 1 Schemas (Preserved untouched)
# ==========================================

class AskRequest(BaseModel):
    question: str = Field(
        ...,
        min_length=1,
        description="The question or prompt submitted by the student",
        examples=["Explain the difference between a process and a thread."]
    )


class AskResponse(BaseModel):
    answer: str = Field(
        ...,
        description="The response generated by the local language model"
    )


# ==========================================
# Exercise 3 Schemas (RAG & Comparison)
# ==========================================

class RetrievedChunk(BaseModel):
    chunk_id: str = Field(..., description="Unique chunk identifier")
    doc_id: str = Field(..., description="Source document ID")
    doc_title: str = Field(..., description="Human-readable document title")
    section: str = Field(..., description="Section title where chunk originated")
    similarity_score: float = Field(..., description="Cosine similarity score relative to query")
    text: str = Field(..., description="Context content text")


class RagRequest(BaseModel):
    question: str = Field(
        ...,
        min_length=1,
        description="The university question submitted by the student",
        examples=["What is the minimum attendance requirement and can it be condoned?"]
    )
    top_k: int = Field(
        default=3,
        ge=1,
        le=10,
        description="Number of most relevant context chunks to retrieve"
    )


class RagResponse(BaseModel):
    question: str
    answer: str
    retrieved_chunks: List[RetrievedChunk]
    grounding_summary: str


class CompareRequest(BaseModel):
    question: str = Field(
        ...,
        min_length=1,
        description="Question to compare across Direct LLM and RAG",
        examples=["What happens if my CGPA falls below 5.0?"]
    )
    top_k: int = Field(
        default=3,
        ge=1,
        le=10,
        description="Number of context chunks to retrieve for the RAG arm"
    )


class CompareResponse(BaseModel):
    question: str
    direct_answer: str
    rag_answer: str
    retrieved_chunks: List[RetrievedChunk]


# ==========================================
# Exercise 4 Schemas (Microservices & Trace)
# ==========================================

class RetrieveRequest(BaseModel):
    query: str = Field(..., min_length=1, description="Query to search knowledge base")
    top_k: int = Field(default=3, ge=1, le=10, description="Number of chunks to return")


class RetrieveResponse(BaseModel):
    query: str
    top_k: int
    retrieved_chunks: List[RetrievedChunk]


class GenerateRequest(BaseModel):
    prompt: str = Field(..., min_length=1, description="Prompt text to feed into LLM")
    model: Optional[str] = Field(default=None, description="Optional target LLM model name")


class GenerateResponse(BaseModel):
    answer: str
    model: str


class TraceStep(BaseModel):
    step: int
    service: str
    action: str
    status: str
    elapsed_ms: float


class OrchestrateRequest(BaseModel):
    question: str = Field(
        ...,
        min_length=1,
        description="Question to orchestrate across microservices",
        examples=["What is the minimum attendance requirement and can it be condoned?"]
    )
    top_k: int = Field(
        default=3,
        ge=1,
        le=10,
        description="Number of context chunks to retrieve"
    )


class OrchestrateResponse(BaseModel):
    question: str
    answer: str
    retrieved_chunks: List[RetrievedChunk]
    orchestration_trace: List[TraceStep]
    total_elapsed_ms: float
